BF: do not pass argv to argparse parser.
in the newest argparse version available in python 2.7.3,
the user of parser.parse_args(argv) was causing:

$ ./pelitagame
Traceback (most recent call last):
  File "./pelitagame", line 362, in <module>
    run_game(*sys.argv[1:])
  File "./pelitagame", line 236, in run_game
    args = parser.parse_args(argv)
  File "/usr/lib/python2.7/argparse.py", line 1688, in parse_args
    args, argv = self.parse_known_args(args, namespace)
  File "/usr/lib/python2.7/argparse.py", line 1720, in parse_known_args
    namespace, args = self._parse_known_args(args, namespace)
  File "/usr/lib/python2.7/argparse.py", line 1929, in _parse_known_args
    stop_index = consume_positionals(start_index)
  File "/usr/lib/python2.7/argparse.py", line 1885, in consume_positionals
    take_action(action, args)
  File "/usr/lib/python2.7/argparse.py", line 1778, in take_action
    argument_values = self._get_values(action, argument_strings)
  File "/usr/lib/python2.7/argparse.py", line 2180, in _get_values
    arg_strings.remove('--')
AttributeError: 'tuple' object has no attribute 'remove'